### ISSUE TITLE
Can this be used to send an sms to a user after they do a certain action like order a product in the app? or its just used to send verification codes?

### ISSUE THREAD

**Issue by francishero** [karimabdelhameed/verification#1]

**Comment by karimabdelhameed** [comment]
Hello @francishero  : thanks for reaching out . 
You can use this module to send SMS to your application users and then verify this code . 
But , of course you have to use sending / verifying SMS by either **[Firebase](https://firebase.google.com/docs/auth/android/phone-auth)** authentication APIs  , or using 
you own server APIs like **[Twilio](https://www.twilio.com/docs/sms/api)** .
